### ISSUE TITLE
Is it possible to use nanoserver instead of windowsservercore?

### ISSUE THREAD

**Issue by andreymir** [pizycki/RavenCage-3.5#6]
Have you tried changing the base image to `microsoft/nanoserver`? It is only 300 MB and `microsoft/windowsservercore` is 4 GB.

**Comment by pizycki** [comment]
Quite time ago, but back then, I was real newbie in containers and have failed pretty fast.
If I remember correctly, I was not able to run Nano container on Windows Server without using HyperV mode. But that was September or even June.
I did the same thing just a moment ago (WinSrv16 build 14393) and it worked without any problem.
It'd be really nice to be able run RavenDB on top of tiny Nano images.

**Comment by pizycki** [comment]
I've found this post
https://windowsserver.uservoice.com/forums/295068-nano-server/suggestions/8106009-enable-full-net-framework-on-nano

To run RavenDB we need .NET framework which is not installed on Windows Nano by default.
The Windows Server Team strongly discourages to use whole .NET framework on this platform. Instead of choosing Nano, they suggest to consider using Windows Server Core image.
I think that's why [official IIS image](https://hub.docker.com/r/microsoft/iis/) is not released on [Nano image](https://hub.docker.com/r/microsoft/nanoserver/).

**Comment by pizycki** [comment]
I'm closing this for now.
